update to 4ece6c5 of iovisor to pull in #139
weaveworks/tcptracer-bpf pull request #61
Opened 2018-08-27 08:05 UTC by dholbach

I updated the vendored bits from `gobpf` in order to pull in the latest, https://github.com/iovisor/gobpf/pull/139 in particular (which brings more clarity in terms of licensing). For the update, I ran
```sh
$  gvt update github.com/iovisor/gobpf/elf
$  gvt update github.com/iovisor/gobpf/pkg/bpffs
$  gvt update github.com/iovisor/gobpf/pkg/cpuonline
```

A local test-build still passes. I wasn't quite sure how else to test this.

2018-08-27 08:55 UTC, schu requested changes
`bpf_map.h` is missing. Forgot to `git add` it?

2018-08-28 15:29 UTC, dholbach commented
To test this, I did a local test with scope (using a new vendored copy of `tcptracer-bpf`) and it built and ran just fine.

2018-08-28 15:51 UTC, bboreham approved these changes

2018-08-28 15:51 UTC, merged

2018-08-28 15:51 UTC, bboreham commented
Thanks!